optimize = "ReleaseSmall"

[modules."lib/hello.zigar"]
source = "zig/hello.zig"

[[targets]]
platform = "linux"
arch = "x64"

#[[targets]]
#platform = "linux"
#arch = "arm64"

#[[targets]]
#platform = "linux-musl"
#arch = "x64"

#[[targets]]
#platform = "linux-musl"
#arch = "arm64"
