optimize = "ReleaseSmall"

[sourceFiles]
"lib/sepia.zigar" = "zig/sepia.zig"

[[targets]]
platform = "linux"
arch = "x64"

[[targets]]
platform = "linux"
arch = "arm64"

[[targets]]
platform = "linux-musl"
arch = "x64"

[[targets]]
platform = "linux-musl"
arch = "arm64"
