optimize = "ReleaseSmall"

[sourceFiles]
"lib/sha1.zigar" = "zig/sha1.zig"

[[targets]]
platform = "linux"
arch = "x64"

[[targets]]
platform = "linux"
arch = "arm64"

[[targets]]
platform = "linux-musl"
arch = "x64"

[[targets]]
platform = "linux-musl"
arch = "arm64"
