optimize = "ReleaseSmall"

[modules."lib/scale.zigar"]
source = "zig/scale.zig"
loader = "src/scale.js"

[modules."lib/sepia.zigar"]
source = "zig/sepia.zig"
loader = "src/sepia.js"

[[targets]]
platform = "linux"
arch = "x64"

[[targets]]
platform = "linux"
arch = "arm64"

[[targets]]
platform = "linux-musl"
arch = "x64"

[[targets]]
platform = "linux-musl"
arch = "arm64"
