#!/usr/bin/env bash

cd "$(dirname "$0")"
tar -h                 `# follow symlink`\
--exclude=.zig-cache   `# ignore cache folder`\
-I "zstd -19"          `# use zstd, max compression level`\
-cf ./src/zig.tar.zstd `# create archive, specifying filename`\
-C ./zig               `# change to directory first`\
.
sha1sum ./src/zig.tar.zstd | cut -d " " -f 1 -z > ./src/zig.tar.zstd.sha1
